// Versi 2 dan Versi 3 latihan Bahasa Indonesia IYSLO Level 4.
// Setiap nomor menguji topik/keterampilan yang sama dengan nomor yang sama di Versi 1 (dan naskah asli),
// tetapi teks, kalimat, dan pilihan jawabannya baru. Pilihan jawaban benar ditulis pertama (ans "A"),
// lalu diacak saat quiz dimulai. Hint tidak boleh menyebut huruf pilihan.

const mc = (q, right, wrong, hint, P) => ({
  type: "mc", q, opts: [right, ...wrong], ans: "A", hint,
  ...(P ? { passage: P.html, passageTitle: P.title } : {}),
});

/* ====================== VERSI 2 ====================== */
const V2P1 = {
  title: "Teks untuk soal nomor 1–5",
  html: `<p>Di banyak rumah, sampah masih dibuang bercampur dalam satu wadah. Akibatnya, sisa makanan yang sebenarnya dapat dijadikan kompos ikut menumpuk di tempat pembuangan akhir bersama plastik dan kaca. Padahal, kebiasaan memilah di rumah ikut menentukan seberapa banyak sampah yang dapat didaur ulang. Wadah yang tidak tersedia, label yang membingungkan, atau jadwal pengangkutan yang tidak teratur membuat warga enggan memilah.</p>
    <p>Sebaliknya, wadah terpisah yang jelas, jadwal angkut sesuai jenis sampah, dan bank sampah yang mudah dijangkau dapat mendorong warga memilah dengan tertib. Dengan kata lain, upaya mengurangi sampah tidak cukup dilakukan dengan imbauan saja. Pemerintah daerah juga harus memastikan sistem pengangkutan dan pengolahan menyambung dari rumah warga hingga tempat pengolahan.</p>`,
};
const V2P2 = {
  title: "Teks untuk soal nomor 6–8",
  html: `<p>Panas matahari membuat air di laut, sungai, dan danau menguap menjadi uap air. Uap air itu naik ke atmosfer, lalu mendingin dan mengembun menjadi titik-titik air yang membentuk awan. Akibatnya, awan yang semakin padat tidak lagi mampu menahan titik-titik air tersebut. Ketika titik air menjadi cukup berat, ia jatuh ke bumi sebagai hujan. Oleh sebab itu, hujan dapat dipahami sebagai bagian dari siklus air yang berlangsung terus-menerus.</p>`,
};
const V2P3 = {
  title: "Teks untuk soal nomor 14–18 (kutipan cerpen)",
  html: `<p>Pagi-pagi sekali, Nadia melihat ibunya mengelap mesin jahit tua di ruang tamu. Pedal besinya berkarat dan jarumnya sering patah, tetapi mesin itu satu-satunya yang membuat dapur rumah mereka tetap mengepul.</p>
    <p>Siang itu, Nadia pulang membawa formulir lomba merancang busana. Juara pertama akan mendapat beasiswa kursus desain yang sejak lama ia impikan. Gambar rancangannya sudah dipuji gurunya sebagai karya paling berani di kelas. Namun, ketika membaca bahwa setiap peserta wajib menyerahkan busana jadi, Nadia terdiam. Biaya kain dan ongkos menjahitnya hampir sama dengan biaya menservis mesin jahit ibunya.</p>
    <p>Menjelang malam, ibu menepuk-nepuk mesin jahitnya sambil menghela napas.</p>
    <p>“Jarumnya patah lagi,” kata ibu sambil tersenyum letih.</p>
    <p>Nadia melipat formulir itu dan menyelipkannya ke dalam buku gambar.</p>
    <p>“Besok kita ke tukang servis, Bu.”</p>`,
};
const V2P4 = {
  title: "Teks untuk soal nomor 19–21 (puisi)",
  html: `<p><b>SENJA DI DERMAGA</b></p>
    <p class="poem">Senja memeluk dermaga yang sepi<br>membisikkan doa pada ombak yang pulang<br>seharian rindu berlayar tanpa arah<br>kini perahu menemukan tambatannya</p>`,
};

const BAHASA_V2 = [
  mc(`Gagasan utama teks tersebut adalah ....`,
    "Ketersediaan sistem pengelolaan sampah ikut menentukan kebiasaan warga dalam memilah sampah.",
    ["Sampah organik lebih berbahaya daripada sampah plastik.", "Warga tidak mau memilah sampah karena memang malas.", "Bank sampah wajib dibangun di setiap rumah."],
    `Gagasan utama adalah inti seluruh teks. Paragraf 1 menjelaskan warga enggan memilah karena wadah, label, dan jadwal angkut bermasalah. Paragraf 2 menjelaskan sistem yang jelas mendorong warga memilah. Intinya: <b>sistem pengelolaan sampah memengaruhi kebiasaan memilah</b>. Pilihan lain tidak menjadi inti teks.`, V2P1),
  mc(`Informasi yang secara tersurat terdapat dalam teks adalah ....`,
    "Wadah yang tidak tersedia dan jadwal angkut yang tidak teratur dapat membuat warga enggan memilah sampah.",
    ["Semua rumah tangga sudah memilah sampah organik dan anorganik.", "Imbauan saja terbukti paling efektif mengurangi sampah.", "Bank sampah hanya bermanfaat bagi petugas kebersihan."],
    `Tersurat artinya tertulis langsung. Paragraf 1 menyebut wadah yang tidak tersedia, label yang membingungkan, dan jadwal angkut yang tidak teratur "membuat warga enggan memilah". Pilihan lain bertentangan dengan teks (teks justru menyebut imbauan saja tidak cukup) atau tidak disebut sama sekali.`, V2P1),
  mc(`Berdasarkan teks, dapat disimpulkan bahwa keberhasilan pemilahan sampah juga ditentukan oleh ....`,
    "mudahnya warga memakai wadah terpisah dan layanan angkut yang sesuai jenis sampah",
    ["harga barang berkemasan yang semakin murah", "banyaknya pabrik daur ulang di luar negeri", "larangan total menggunakan kemasan"],
    `Paragraf 2 menyebut wadah terpisah yang jelas, jadwal angkut sesuai jenis, dan bank sampah yang mudah dijangkau mendorong warga memilah. Jadi kuncinya adalah <b>kemudahan warga memilah dan layanan yang sesuai</b>. Harga kemasan, pabrik luar negeri, dan larangan total tidak dibahas.`, V2P1),
  mc(`Pernyataan berikut yang merupakan informasi tersirat dalam teks adalah ....`,
    "Pengelolaan sampah perlu dirancang sebagai rangkaian yang saling menyambung dari rumah hingga tempat pengolahan.",
    ["Sisa makanan tidak boleh dijadikan kompos.", "Pengangkutan sampah adalah satu-satunya masalah persampahan.", "Warga pada dasarnya tidak peduli pada kebersihan lingkungan."],
    `Tersirat artinya tidak ditulis langsung tetapi dapat dipahami. Teks menuntut sistem yang "menyambung dari rumah warga hingga tempat pengolahan", sehingga tersirat bahwa pengelolaan sampah harus berupa <b>rangkaian yang saling terhubung</b>. Pilihan lain bertentangan dengan teks atau tidak didukung.`, V2P1),
  mc(`Makna kata “menyambung” pada frasa “sistem pengangkutan dan pengolahan menyambung dari rumah warga” adalah ....`,
    "berlangsung bersinambungan tanpa terputus antartahap",
    ["dibuat dari bahan yang saling melekat", "dikerjakan oleh satu petugas saja", "hanya berlaku di lingkungan rumah"],
    `Maknai kata lewat konteks: pengangkutan dan pengolahan harus berjalan dari rumah hingga tempat pengolahan. Artinya tahap-tahapnya <b>bersinambungan dan tidak terputus</b>.`, V2P1),
  mc(`Berdasarkan isi dan pola pengembangannya, teks tersebut termasuk teks ....`,
    "eksplanasi, karena menjelaskan proses dan hubungan sebab-akibat suatu fenomena alam",
    ["deskripsi, karena melukiskan keadaan laut secara rinci", "narasi, karena menceritakan pengalaman tokoh secara berurutan", "persuasi, karena mengajak pembaca menghemat air"],
    `Teks menjelaskan <b>proses</b> (menguap, naik, mengembun, jatuh) dan <b>sebab-akibat</b> terjadinya hujan. Itu ciri teks eksplanasi. Tidak ada tokoh dan alur (narasi), tidak sekadar melukiskan (deskripsi), dan tidak ada ajakan (persuasi).`, V2P2),
  mc(`Kalimat “Akibatnya, awan yang semakin padat tidak lagi mampu menahan titik-titik air tersebut” berfungsi untuk ....`,
    "menunjukkan akibat dari proses yang dijelaskan sebelumnya",
    ["memperkenalkan istilah baru yang belum dijelaskan", "memberi contoh kegiatan manusia di sekitar laut", "menolak pendapat yang dikemukakan sebelumnya"],
    `Kata "Akibatnya" menandai hubungan sebab-akibat. Kalimat sebelumnya menjelaskan uap mengembun menjadi awan, dan kalimat ini menyebut <b>akibat</b>-nya: awan makin padat dan tidak mampu menahan titik air.`, V2P2),
  mc(`Jika kalimat terakhir dihapus, perubahan utama pada susunan teks adalah ....`,
    "teks kehilangan bagian yang menegaskan simpulan dari penjelasan sebelumnya",
    ["teks tidak lagi menjelaskan proses terbentuknya awan", "urutan proses menjadi sepenuhnya tidak masuk akal", "teks berubah dari eksplanasi menjadi persuasi"],
    `Kalimat terakhir ("Oleh sebab itu, hujan dapat dipahami sebagai bagian dari siklus air ...") adalah <b>simpulan</b> dari seluruh uraian. Jika dihapus, penjelasan proses tetap utuh dan jenis teks tetap eksplanasi. Yang hilang hanya penegasan simpulannya.`, V2P2),
  mc(`Kalimat yang paling efektif adalah ....`,
    "Para tamu diharapkan segera mengisi buku daftar hadir.",
    ["Para tamu-tamu diharapkan untuk segera mengisi buku daftar hadir.", "Tamu-tamu diharapkan agar supaya segera mengisi buku daftar hadir.", "Kepada para tamu diharapkan dapat segera mengisi buku daftar hadir."],
    `Kalimat efektif hemat kata dan bersubjek jelas. Memakai "para" sekaligus "tamu-tamu" berlebihan karena sama-sama jamak. "Agar supaya" juga pleonasme. Kalimat yang diawali "Kepada" tidak punya subjek. Kalimat yang benar singkat, jelas, dan bersubjek.`),
  mc(`Perhatikan kalimat berikut!<br><br>Sesudah membaca pengumuman itu Budi berseru “Besok kita berkumpul di aula”.<br><br>Perbaikan tanda baca yang paling tepat adalah ....`,
    "Sesudah membaca pengumuman itu, Budi berseru, “Besok kita berkumpul di aula.”",
    ["Sesudah membaca pengumuman itu Budi berseru, “Besok kita berkumpul di aula.”", "Sesudah membaca pengumuman itu, Budi berseru “Besok kita berkumpul di aula”.", "Sesudah membaca pengumuman itu; Budi berseru, “Besok kita berkumpul di aula.”"],
    `Tiga aturan: (1) anak kalimat yang mendahului induk kalimat dipisah koma; (2) sebelum kutipan langsung diberi koma; (3) tanda titik di akhir kutipan langsung diletakkan <b>di dalam</b> tanda petik penutup. Hanya satu pilihan yang memenuhi ketiganya.`),
  mc(`Kata baku digunakan secara tepat dalam kalimat ....`,
    "Pengemudi harus memahami risiko berkendara di jalan licin.",
    ["Dokter meresepkan obat dari apotik terdekat.", "Ayah memberi nasehat kepada kami.", "Kami memperhatikan jadual pelajaran yang baru."],
    `Bentuk baku yang benar: <b>risiko</b> (bukan "resiko"), <b>apotek</b> (bukan "apotik"), <b>nasihat</b> (bukan "nasehat"), <b>jadwal</b> (bukan "jadual"). Hanya satu kalimat yang seluruh katanya baku.`),
  mc(`Perhatikan kalimat berikut!<br><br>Dokter memeriksa pasien dengan stetoskop.<br><br>Kalimat tersebut ambigu. Jika yang dimaksud adalah dokter menggunakan stetoskop untuk memeriksa pasien, perbaikan yang paling tepat adalah ....`,
    "Dengan menggunakan stetoskop, dokter memeriksa pasien.",
    ["Dengan pasien, dokter memeriksa stetoskop.", "Dokter dengan stetoskop memeriksa pasien.", "Pasien memeriksa dokter menggunakan stetoskop."],
    `Kalimat asli ambigu: "dengan stetoskop" bisa berarti alat pemeriksaan atau pasien yang membawa stetoskop. Agar jelas bahwa stetoskop adalah alat, tulis "<b>Dengan menggunakan stetoskop</b>, dokter memeriksa pasien." Pilihan lain masih ambigu atau mengubah makna.`),
  mc(`Perhatikan kalimat berikut!<br><br>Sinta tetap tersenyum _____ hatinya sedang bersedih.<br><br>Konjungsi yang paling tepat untuk melengkapi kalimat tersebut adalah ....`,
    "Walaupun", ["Sehingga", "Sebab", "Supaya"],
    `Tetap tersenyum <i>padahal</i> hati bersedih adalah pertentangan, sehingga butuh konjungsi konsesif <b>walaupun</b>. "Sehingga" menyatakan akibat, "sebab" menyatakan alasan, "supaya" menyatakan tujuan.`),
  mc(`Konflik utama yang dialami Nadia adalah ....`,
    "menimbang antara ikut lomba dan menolong menservis mesin jahit ibu",
    ["memutuskan perlu tidaknya membeli mesin jahit baru", "meyakinkan gurunya bahwa rancangannya layak dilombakan", "meminta ibu membiayai kain untuk busananya"],
    `Konflik batin muncul ketika biaya busana lomba hampir sama dengan biaya servis mesin jahit ibu. Nadia harus memilih antara <b>keinginannya ikut lomba</b> dan <b>kebutuhan ibunya</b>.`, V2P3),
  mc(`Watak Nadia yang paling kuat ditunjukkan pada bagian akhir cerita adalah ....`,
    "peduli", ["angkuh", "pemarah", "ceroboh"],
    `Di akhir cerita Nadia menyimpan formulir lomba dan menawarkan diri mengantar mesin jahit ke tukang servis. Sikap itu menunjukkan ia <b>peduli</b> pada ibunya.`, V2P3),
  mc(`Kalimat “Nadia melipat formulir itu dan menyelipkannya ke dalam buku gambar” terutama berfungsi untuk ....`,
    "menyiratkan keputusan Nadia tanpa menyebutkannya secara terang-terangan",
    ["menunjukkan bahwa Nadia tidak mengerti syarat lomba", "menunjukkan bahwa lomba itu ditunda", "menjelaskan bahwa Nadia kecewa kepada ibunya"],
    `Pengarang tidak menulis "Nadia memutuskan tidak ikut lomba", tetapi menunjukkannya lewat tindakan melipat dan menyimpan formulir. Ini teknik <i>show, don't tell</i> yang <b>menyiratkan keputusan</b> tokoh.`, V2P3),
  mc(`Amanat yang paling sesuai dengan keseluruhan cerita adalah ....`,
    "Kepedulian membuat seseorang memikirkan kepentingan orang lain saat mengambil keputusan.",
    ["Keinginan pribadi harus selalu dikalahkan oleh kebutuhan keluarga.", "Lomba hanya layak diikuti oleh orang yang mampu secara ekonomi.", "Alat yang sudah tua sebaiknya segera dibuang."],
    `Amanat harus sesuai seluruh cerita tanpa berlebihan. Nadia memilih membantu ibunya karena peduli. Pilihan yang memakai kata "selalu" terlalu mutlak, dan dua pilihan lain tidak punya dasar di cerita.`, V2P3),
  mc(`Judul yang paling mampu mewakili konflik sekaligus makna cerita tersebut adalah ....`,
    "Formulir yang Terlipat", ["Mesin Jahit Berkarat", "Beasiswa Impian", "Lomba Rancang Busana"],
    `Judul yang baik mewakili konflik dan makna cerita. "Formulir yang Terlipat" melambangkan keputusan Nadia melepas keinginannya demi ibu. Judul lain hanya menyebut sebagian unsur cerita.`, V2P3),
  mc(`Larik “Senja memeluk dermaga yang sepi” menggunakan majas ....`,
    "Personifikasi", ["Hiperbola", "Ironi", "Eufemisme"],
    `Senja adalah benda alam, tetapi digambarkan <i>memeluk</i> seperti manusia. Memberi sifat atau perbuatan manusia pada benda mati disebut <b>personifikasi</b>.`, V2P4),
  mc(`Makna keseluruhan puisi tersebut paling dekat dengan ....`,
    "kerinduan dan pencarian arah yang akhirnya menemukan tempat berlabuh",
    ["ketakutan nelayan menghadapi ombak besar", "keinginan seseorang meninggalkan kampung halaman", "penyesalan karena senja datang terlalu cepat"],
    `Larik awal menggambarkan rindu yang berlayar "tanpa arah", dan larik akhir menyebut perahu "menemukan tambatannya". Artinya <b>pencarian yang berakhir dengan ketenangan atau tempat berlabuh</b>.`, V2P4),
  mc(`Larik “kini perahu menemukan tambatannya” dapat ditafsirkan sebagai ....`,
    "seseorang akhirnya menemukan tempat atau tujuan yang membuatnya tenang",
    ["perahu yang diikat agar tidak dicuri", "perbaikan dermaga setelah badai", "bertambahnya jumlah nelayan di dermaga"],
    `Larik ini bermakna kias. "Perahu" melambangkan orang yang mencari, "tambatan" melambangkan tempat berlabuh. Jadi maknanya seseorang <b>akhirnya menemukan tujuan atau ketenangan</b>.`, V2P4),
  mc(`Perhatikan dua pernyataan berikut!<br><br><b>Pernyataan I:</b><br>“Pekerjaan rumah harus dihapus karena pasti membuat siswa stres.”<br><br><b>Pernyataan II:</b><br>“Pekerjaan rumah perlu diatur jumlah dan jenisnya karena dapat membebani siswa sekaligus melatih kemandirian belajar.”<br><br>Pernyataan II menunjukkan penalaran yang lebih kuat karena ....`,
    "mempertimbangkan lebih dari satu dampak pekerjaan rumah",
    ["menggunakan lebih banyak kata sambung", "tidak memuat alasan apa pun", "menyatakan bahwa pekerjaan rumah tidak pernah menimbulkan masalah"],
    `Penalaran kuat tidak menggeneralisasi. Pernyataan I memakai kata mutlak ("pasti"), sedangkan Pernyataan II menimbang <b>dua dampak</b> (membebani dan melatih kemandirian) lalu memberi solusi (diatur).`),
  mc(`Perhatikan pernyataan berikut!<br><br>Sejak sekolah menambah jam pelajaran olahraga, nilai ulangan matematika siswa meningkat. Dengan demikian, olahraga pasti menjadi satu-satunya penyebab naiknya nilai matematika.<br><br>Kelemahan penalaran pada pernyataan tersebut adalah ....`,
    "dua peristiwa yang berurutan langsung dianggap berhubungan sebab-akibat yang pasti",
    ["simpulan tidak menyinggung olahraga sama sekali", "penulis tidak menjelaskan pengertian nilai ulangan", "simpulan sepenuhnya bertentangan dengan informasi sebelumnya"],
    `Ini kesalahan <i>post hoc</i>: karena satu kejadian terjadi setelah kejadian lain, langsung disimpulkan yang pertama adalah penyebab pasti dan satu-satunya. Bisa jadi ada faktor lain, misalnya cara mengajar atau belajar mandiri.`),
  mc(`Perhatikan pernyataan dalam iklan berikut!<br><br>“Sepatu Z dipakai oleh banyak pelari cepat. Pakailah Z setiap hari agar larimu secepat mereka!”<br><br>Penilaian paling kritis terhadap pernyataan tersebut adalah ....`,
    "Kecepatan pelari tidak dapat langsung dianggap akibat memakai sepatu itu tanpa bukti yang memadai.",
    ["Klaim itu pasti benar karena banyak pelari cepat memakainya.", "Semua iklan pada dasarnya berbohong.", "Sepatu tidak mungkin memengaruhi cara seseorang berlari."],
    `Berpikir kritis berarti menguji hubungan sebab-akibat. Pelari cepat memakai sepatu itu belum membuktikan sepatu itulah penyebab kecepatannya (korelasi bukan sebab-akibat). Perlu <b>bukti yang memadai</b>. Pilihan lain terlalu percaya atau terlalu ekstrem.`),
  mc(`Perhatikan paragraf berikut!<br><br>Taman sekolah kini dibuka sampai sore hari. Dalam sebulan terakhir, jumlah siswa yang berkunjung setelah jam pelajaran bertambah. Sebagian siswa memakai waktu itu untuk berdiskusi, sedangkan sebagian lainnya berlatih membaca puisi atau menggambar. Melihat keadaan tersebut, sekolah berencana menambah bangku dan tempat berteduh.<br><br>Simpulan yang paling logis dan tidak melampaui informasi dalam teks adalah ....`,
    "Taman sekolah setelah jam pelajaran dimanfaatkan siswa untuk beberapa kegiatan.",
    ["Seluruh siswa lebih betah di taman daripada di kelas.", "Pembukaan taman sampai sore membuat prestasi siswa meningkat.", "Berlatih membaca puisi adalah alasan utama bertambahnya pengunjung."],
    `Simpulan yang aman hanya memakai informasi yang ada: siswa memanfaatkan taman setelah jam pelajaran untuk berdiskusi, membaca puisi, dan menggambar. Pilihan "seluruh siswa", "prestasi meningkat", dan "alasan utama" <b>melampaui</b> informasi teks.`),
];

/* ====================== VERSI 3 ====================== */
const V3P1 = {
  title: "Teks untuk soal nomor 1–5",
  html: `<p>Di banyak kota, pasar tradisional dipandang kumuh dan ketinggalan zaman. Akibatnya, pembenahan pasar sering kalah prioritas dibandingkan pembangunan pusat perbelanjaan modern. Padahal, kebersihan dan kemudahan akses pasar ikut menentukan pilihan warga untuk berbelanja. Lantai yang becek, lorong yang sempit, lapak yang tidak tertata, dan lahan parkir yang sulit membuat pembeli berpindah ke tempat lain.</p>
    <p>Sebaliknya, pasar yang bersih, terang, tertata, dan terhubung dengan angkutan umum dapat menarik pembeli kembali. Dengan kata lain, upaya menghidupkan pasar tradisional tidak cukup dengan menambah jumlah kios. Pemerintah kota juga perlu memastikan pasar mudah dijangkau serta aman dan nyaman bagi pembeli.</p>`,
};
const V3P2 = {
  title: "Teks untuk soal nomor 6–8",
  html: `<p>Ketika hujan deras turun di lereng yang ditumbuhi hutan, akar pepohonan menahan tanah agar tidak mudah terbawa air. Namun, pada lereng yang gundul, tanah tidak lagi tertahan oleh akar. Akibatnya, air hujan membawa lapisan tanah subur ke bagian bawah lereng. Jika proses ini berlangsung terus-menerus, tanah menjadi labil dan longsor dapat terjadi. Oleh karena itu, penanaman pohon di lereng berperan penting dalam mencegah bencana longsor.</p>`,
};
const V3P3 = {
  title: "Teks untuk soal nomor 14–18 (kutipan cerpen)",
  html: `<p>Sejak pagi, Bima beberapa kali menatap sepatu bolanya yang tersimpan di bawah ranjang. Solnya sudah menganga dan talinya tinggal separuh, tetapi hanya itulah sepatu yang ia punya.</p>
    <p>Siang itu, Bima membawa pulang pengumuman turnamen sepak bola antarsekolah. Pelatihnya menyebut Bima layak menjadi pemain inti. Namun, ketika membaca bahwa setiap peserta wajib memakai sepatu bola yang layak, Bima terdiam. Harga sepatu baru hampir sama dengan biaya mengganti ban motor ayahnya.</p>
    <p>Menjelang malam, ayah pulang sambil menuntun motornya.</p>
    <p>“Bannya bocor lagi,” kata ayah sambil mengusap keringat.</p>
    <p>Bima menggulung pengumuman itu lalu memasukkannya ke laci meja.</p>
    <p>“Besok aku bantu menambal bannya, Yah.”</p>`,
};
const V3P4 = {
  title: "Teks untuk soal nomor 19–21 (puisi)",
  html: `<p><b>HUJAN SORE</b></p>
    <p class="poem">Hujan mengetuk atap rumahku<br>membawa dingin di telapak kakinya<br>sehari panas menyimpan banyak gelisah<br>kini tanah menemukan sejuknya kembali</p>`,
};

const BAHASA_V3 = [
  mc(`Gagasan utama teks tersebut adalah ....`,
    "Kebersihan dan kemudahan akses pasar ikut menentukan pilihan warga untuk berbelanja.",
    ["Pusat perbelanjaan modern harus dilarang dibangun di kota.", "Pembeli tidak menyukai barang yang dijual di pasar tradisional.", "Jumlah kios adalah satu-satunya penentu ramainya pasar."],
    `Gagasan utama adalah inti seluruh teks. Paragraf 1 menjelaskan pasar yang kotor dan sulit dijangkau ditinggalkan pembeli. Paragraf 2 menjelaskan pasar yang bersih, tertata, dan mudah dijangkau menarik pembeli. Intinya: <b>kebersihan dan kemudahan akses memengaruhi pilihan warga</b>.`, V3P1),
  mc(`Informasi yang secara tersurat terdapat dalam teks adalah ....`,
    "Lahan parkir yang sulit dapat membuat pembeli berpindah ke tempat lain.",
    ["Semua pasar tradisional di kota sudah bersih dan tertata.", "Pasar tradisional tidak mungkin ramai kembali.", "Menambah jumlah kios terbukti paling efektif menghidupkan pasar."],
    `Tersurat artinya tertulis langsung. Paragraf 1 menyebut lantai becek, lorong sempit, lapak tidak tertata, dan lahan parkir yang sulit "membuat pembeli berpindah ke tempat lain". Pilihan lain bertentangan dengan teks atau tidak disebutkan.`, V3P1),
  mc(`Berdasarkan teks, dapat disimpulkan bahwa upaya menghidupkan pasar tradisional juga dipengaruhi oleh ....`,
    "mudahnya pembeli menjangkau pasar dan nyamannya suasana berbelanja",
    ["harga barang yang selalu lebih murah daripada toko modern", "banyaknya pusat perbelanjaan di sekitar pasar", "larangan penjualan barang impor"],
    `Paragraf 2 menyebut pasar yang bersih, tertata, terhubung angkutan umum, serta mudah dijangkau dan nyaman menarik pembeli. Jadi <b>kemudahan menjangkau dan kenyamanan</b> menjadi faktor penentu. Harga, pusat perbelanjaan, dan barang impor tidak dibahas.`, V3P1),
  mc(`Pernyataan berikut yang merupakan informasi tersirat dalam teks adalah ....`,
    "Menghidupkan pasar tradisional membutuhkan pembenahan lingkungan pasar, bukan sekadar penambahan kios.",
    ["Pembeli tidak membutuhkan angkutan umum untuk ke pasar.", "Pusat perbelanjaan modern adalah satu-satunya penyebab sepinya pasar.", "Pedagang pasar tidak ingin tempatnya dibenahi."],
    `Tersirat artinya tidak ditulis langsung tetapi dapat dipahami. Teks menyebut menambah kios saja tidak cukup dan pasar harus bersih, tertata, serta mudah dijangkau, sehingga tersirat perlunya <b>pembenahan lingkungan pasar</b>. Pilihan lain bertentangan atau tidak didukung teks.`, V3P1),
  mc(`Makna kata “tertata” pada frasa “pasar yang tertata” adalah ....`,
    "disusun teratur sehingga mudah dilalui dan dicari",
    ["dibangun dengan bahan bangunan baru", "hanya berisi pedagang tertentu", "dijaga petugas keamanan setiap saat"],
    `Lihat konteksnya: lorong sempit dan lapak yang tidak tertata membuat pembeli pergi, sedangkan pasar yang tertata menarik pembeli. Jadi "tertata" berarti <b>tersusun teratur</b>.`, V3P1),
  mc(`Berdasarkan isi dan pola pengembangannya, teks tersebut termasuk teks ....`,
    "eksplanasi, karena menjelaskan proses dan hubungan sebab-akibat suatu fenomena",
    ["deskripsi, karena melukiskan keindahan lereng secara rinci", "narasi, karena menceritakan petualangan tokoh secara berurutan", "persuasi, karena memaksa pembaca menanam pohon"],
    `Teks menjelaskan <b>proses</b> (tanah terbawa air, menjadi labil, longsor) dan <b>sebab-akibat</b> gundulnya lereng. Itu ciri teks eksplanasi, bukan deskripsi, narasi, atau persuasi.`, V3P2),
  mc(`Kalimat “Akibatnya, air hujan membawa lapisan tanah subur ke bagian bawah lereng” berfungsi untuk ....`,
    "menunjukkan akibat dari keadaan yang dijelaskan sebelumnya",
    ["memperkenalkan topik yang baru dibahas", "memberi contoh jenis pohon di lereng", "menyangkal isi kalimat sebelumnya"],
    `Kata "Akibatnya" menandai sebab-akibat. Kalimat sebelumnya menyebut lereng gundul tidak lagi memiliki akar penahan, dan kalimat ini menyebut <b>akibat</b>-nya: tanah subur terbawa air.`, V3P2),
  mc(`Jika kalimat terakhir dihapus, perubahan utama pada susunan teks adalah ....`,
    "teks kehilangan bagian yang menegaskan implikasi dari penjelasan sebelumnya",
    ["teks tidak lagi menjelaskan penyebab longsor", "kalimat-kalimat lain menjadi tidak berhubungan sama sekali", "teks berubah dari eksplanasi menjadi narasi"],
    `Kalimat terakhir ("Oleh karena itu, penanaman pohon ...") memuat <b>implikasi atau simpulan</b> dari seluruh penjelasan. Jika dihapus, penjelasan sebab-akibat tetap ada dan teks tetap eksplanasi. Yang hilang hanya penegasan implikasinya.`, V3P2),
  mc(`Kalimat yang paling efektif adalah ....`,
    "Para penonton dimohon tetap tenang selama acara berlangsung.",
    ["Para penonton-penonton dimohon untuk tetap tenang selama acara berlangsung.", "Penonton-penonton dimohon agar supaya tetap tenang selama acara berlangsung.", "Kepada para penonton dimohon untuk dapat tetap tenang selama acara berlangsung."],
    `Kalimat efektif hemat kata dan bersubjek jelas. Memakai "para" sekaligus "penonton-penonton" berlebihan karena sama-sama jamak. "Agar supaya" pleonasme. Kalimat yang diawali "Kepada" tidak punya subjek.`),
  mc(`Perhatikan kalimat berikut!<br><br>Sesudah menimbang usulan itu Ketua berkata “Rapat kita tunda sampai besok”.<br><br>Perbaikan tanda baca yang paling tepat adalah ....`,
    "Sesudah menimbang usulan itu, Ketua berkata, “Rapat kita tunda sampai besok.”",
    ["Sesudah menimbang usulan itu Ketua berkata, “Rapat kita tunda sampai besok.”", "Sesudah menimbang usulan itu, Ketua berkata “Rapat kita tunda sampai besok”.", "Sesudah menimbang usulan itu; Ketua berkata, “Rapat kita tunda sampai besok.”"],
    `Tiga aturan: (1) anak kalimat yang mendahului induk kalimat dipisah koma; (2) sebelum kutipan langsung diberi koma; (3) tanda titik di akhir kutipan langsung diletakkan <b>di dalam</b> tanda petik penutup. Hanya satu pilihan yang memenuhi ketiganya.`),
  mc(`Kata baku digunakan secara tepat dalam kalimat ....`,
    "Silakan ambil formulir di meja pendaftaran.",
    ["Murid-murid mengikuti praktek lapangan hari ini.", "Rumah nenek berada di komplek perumahan itu.", "Setiap siswa harus mentaati tata tertib sekolah."],
    `Bentuk baku yang benar: <b>silakan</b> (bukan "silahkan"), <b>praktik</b> (bukan "praktek"), <b>kompleks</b> (bukan "komplek"), dan <b>menaati</b> (bukan "mentaati"). Hanya satu kalimat yang seluruh katanya baku.`),
  mc(`Perhatikan kalimat berikut!<br><br>Polisi menangkap pencuri dengan borgol.<br><br>Kalimat tersebut ambigu. Jika yang dimaksud adalah polisi menggunakan borgol untuk menangkap pencuri, perbaikan yang paling tepat adalah ....`,
    "Dengan menggunakan borgol, polisi menangkap pencuri.",
    ["Dengan pencuri, polisi menangkap borgol.", "Polisi dengan borgol menangkap pencuri.", "Pencuri menangkap polisi menggunakan borgol."],
    `Kalimat asli ambigu: "dengan borgol" bisa berarti alat penangkapan atau pencuri yang membawa borgol. Agar jelas borgol adalah alat, tulis "<b>Dengan menggunakan borgol</b>, polisi menangkap pencuri." Pilihan lain masih ambigu atau mengubah makna.`),
  mc(`Perhatikan kalimat berikut!<br><br>Rina tetap mengerjakan soal _____ waktunya hampir habis.<br><br>Konjungsi yang paling tepat untuk melengkapi kalimat tersebut adalah ....`,
    "Meskipun", ["Sehingga", "Sebab", "Supaya"],
    `Tetap mengerjakan <i>padahal</i> waktu hampir habis adalah pertentangan, sehingga butuh konjungsi konsesif <b>meskipun</b>. "Sehingga" menyatakan akibat, "sebab" menyatakan alasan, "supaya" menyatakan tujuan.`),
  mc(`Konflik utama yang dialami Bima adalah ....`,
    "menimbang antara ikut turnamen dan menolong ayah mengganti ban motor",
    ["memutuskan perlu tidaknya berganti klub sepak bola", "meyakinkan pelatih bahwa ia layak menjadi pemain inti", "meminta ayah membelikan motor yang baru"],
    `Konflik batin muncul ketika harga sepatu untuk turnamen hampir sama dengan biaya mengganti ban motor ayah. Bima harus memilih antara <b>keinginannya ikut turnamen</b> dan <b>kebutuhan ayahnya</b>.`, V3P3),
  mc(`Watak Bima yang paling kuat ditunjukkan pada bagian akhir cerita adalah ....`,
    "peduli", ["sombong", "pemarah", "ceroboh"],
    `Di akhir cerita Bima menyimpan pengumuman turnamen dan menawarkan diri membantu menambal ban. Sikap itu menunjukkan ia <b>peduli</b> pada ayahnya.`, V3P3),
  mc(`Kalimat “Bima menggulung pengumuman itu lalu memasukkannya ke laci meja” terutama berfungsi untuk ....`,
    "menyiratkan keputusan Bima tanpa menyebutkannya secara terang-terangan",
    ["menunjukkan bahwa Bima tidak membaca syarat turnamen", "menunjukkan bahwa turnamen dibatalkan", "menjelaskan bahwa Bima kecewa kepada pelatihnya"],
    `Pengarang tidak menulis "Bima memutuskan tidak ikut turnamen", tetapi menunjukkannya lewat tindakan menggulung dan menyimpan pengumuman. Ini teknik <i>show, don't tell</i> yang <b>menyiratkan keputusan</b> tokoh.`, V3P3),
  mc(`Amanat yang paling sesuai dengan keseluruhan cerita adalah ....`,
    "Kepedulian membuat seseorang memikirkan kepentingan orang lain saat mengambil keputusan.",
    ["Cita-cita pribadi harus selalu dikalahkan oleh kebutuhan keluarga.", "Turnamen hanya pantas diikuti oleh peserta yang punya banyak uang.", "Peralatan yang rusak sebaiknya dibiarkan saja."],
    `Amanat harus sesuai seluruh cerita tanpa berlebihan. Bima memilih membantu ayahnya karena peduli. Pilihan yang memakai kata "selalu" terlalu mutlak, dan dua pilihan lain tidak punya dasar di cerita.`, V3P3),
  mc(`Judul yang paling mampu mewakili konflik sekaligus makna cerita tersebut adalah ....`,
    "Pengumuman di Dalam Laci", ["Sepatu Bola Baru", "Turnamen Antarsekolah", "Motor Ayah"],
    `Judul yang baik mewakili konflik dan makna cerita. "Pengumuman di Dalam Laci" melambangkan keputusan Bima menyimpan keinginannya demi ayah. Judul lain hanya menyebut sebagian unsur cerita.`, V3P3),
  mc(`Larik “Hujan mengetuk atap rumahku” menggunakan majas ....`,
    "Personifikasi", ["Hiperbola", "Ironi", "Eufemisme"],
    `Hujan adalah benda alam, tetapi digambarkan <i>mengetuk</i> seperti manusia. Memberi sifat atau perbuatan manusia pada benda mati disebut <b>personifikasi</b>.`, V3P4),
  mc(`Makna keseluruhan puisi tersebut paling dekat dengan ....`,
    "perubahan dari kegelisahan menuju kelegaan dan ketenangan",
    ["ketakutan seseorang menghadapi badai", "keinginan seseorang pergi ke luar rumah saat sore", "penyesalan karena hari terlalu cepat berganti"],
    `Larik awal menyebut hari yang panas "menyimpan banyak gelisah", dan larik akhir menyebut tanah "menemukan sejuknya kembali". Maknanya <b>perubahan dari gelisah menuju lega dan tenang</b>.`, V3P4),
  mc(`Larik “kini tanah menemukan sejuknya kembali” dapat ditafsirkan sebagai ....`,
    "kelegaan dan ketenangan hadir kembali setelah masa yang menekan",
    ["tanah yang digali untuk membuat sumur", "pergantian sore menjadi malam", "bertambahnya sampah di halaman rumah"],
    `Larik ini bermakna kias. "Tanah" mewakili keadaan atau perasaan yang tadinya panas dan gelisah, "sejuk" melambangkan <b>lega dan tenang</b> yang datang kembali setelah masa menekan.`, V3P4),
  mc(`Perhatikan dua pernyataan berikut!<br><br><b>Pernyataan I:</b><br>“Buku cetak harus ditiadakan karena buku digital pasti lebih baik.”<br><br><b>Pernyataan II:</b><br>“Buku cetak dan buku digital sebaiknya dipakai sesuai kebutuhan karena masing-masing memiliki kelebihan dan kekurangan.”<br><br>Pernyataan II menunjukkan penalaran yang lebih kuat karena ....`,
    "mempertimbangkan kelebihan dan kekurangan lebih dari satu pilihan",
    ["kalimatnya lebih panjang daripada pernyataan pertama", "tidak memuat alasan apa pun", "menyatakan bahwa buku cetak sama sekali tidak diperlukan"],
    `Penalaran kuat tidak menggeneralisasi. Pernyataan I memakai kata mutlak ("pasti"), sedangkan Pernyataan II menimbang <b>kelebihan dan kekurangan dua pilihan</b> lalu menyarankan pemakaian sesuai kebutuhan.`),
  mc(`Perhatikan pernyataan berikut!<br><br>Sejak ayah rutin membaca koran setiap pagi, adik kini rajin bangun pagi. Dengan demikian, kebiasaan ayah membaca koran pasti menjadi satu-satunya sebab adik rajin bangun pagi.<br><br>Kelemahan penalaran pada pernyataan tersebut adalah ....`,
    "dua peristiwa yang berurutan langsung dianggap berhubungan sebab-akibat yang pasti",
    ["simpulan tidak menyinggung koran sama sekali", "penulis tidak menjelaskan arti rajin", "simpulan sepenuhnya bertentangan dengan informasi sebelumnya"],
    `Ini kesalahan <i>post hoc</i>: karena satu kejadian terjadi setelah kejadian lain, langsung disimpulkan yang pertama adalah penyebab pasti dan satu-satunya. Bisa jadi ada faktor lain, misalnya jam tidur atau jadwal sekolah.`),
  mc(`Perhatikan pernyataan dalam iklan berikut!<br><br>“Jus M diminum oleh banyak siswa peraih nilai tertinggi. Minumlah M setiap hari agar kamu pun mendapat nilai tertinggi!”<br><br>Penilaian paling kritis terhadap pernyataan tersebut adalah ....`,
    "Nilai tinggi siswa tidak dapat langsung dianggap akibat minum produk itu tanpa bukti yang memadai.",
    ["Klaim itu pasti benar karena banyak siswa pandai meminumnya.", "Semua iklan pada dasarnya tidak dapat dipercaya.", "Minuman tidak mungkin memengaruhi kesehatan seseorang."],
    `Berpikir kritis berarti menguji hubungan sebab-akibat. Siswa berprestasi minum produk itu belum membuktikan produk itulah penyebab nilainya (korelasi bukan sebab-akibat). Perlu <b>bukti yang memadai</b>. Pilihan lain terlalu percaya atau terlalu ekstrem.`),
  mc(`Perhatikan paragraf berikut!<br><br>Lapangan sekolah mulai dibuka hingga sore hari. Dalam sebulan terakhir, jumlah siswa yang datang setelah jam pelajaran bertambah. Sebagian siswa memakai waktu itu untuk berlatih basket, sedangkan sebagian lainnya berlatih senam atau berlari. Melihat keadaan itu, sekolah berencana memasang lampu tambahan.<br><br>Simpulan yang paling logis dan tidak melampaui informasi dalam teks adalah ....`,
    "Lapangan sekolah setelah jam pelajaran dimanfaatkan siswa untuk beberapa kegiatan.",
    ["Seluruh siswa lebih suka berolahraga daripada belajar di kelas.", "Pembukaan lapangan hingga sore membuat prestasi olahraga siswa meningkat.", "Berlari adalah alasan utama bertambahnya jumlah siswa yang datang."],
    `Simpulan yang aman hanya memakai informasi yang ada: siswa memanfaatkan lapangan setelah jam pelajaran untuk basket, senam, dan berlari. Pilihan "seluruh siswa", "prestasi meningkat", dan "alasan utama" <b>melampaui</b> informasi teks.`),
];
